/* data.js — ข้อมูลข่าววันนี้ (หุ่นยนต์คลาวด์เขียนทับไฟล์นี้ทุกเช้า 6 โมง แล้ว push)
   ไทยเป็นหลัก + หย่อดศัพท์อังกฤษ (แตะแปลได้) · terms = คำอังกฤษ→คำแปลไทย */
window.TODAY_DATA = {
  "date": "2026-08-01",
  "summary": "วันนี้มีข่าว ‘เกี่ยวตรง’ กับเรา 3 ข่าว เด่นสุดคือการบินไทยเซ็น MRO อู่ตะเภา (ตรงกับดีล Hanko) และทุนญี่ปุ่น/ชิ้นส่วน EV ยังขยาย = โอกาสลูกค้าใหม่. จุดเสี่ยง: การผลิตรถ ICE หด ควรเฝ้าลูกค้ากลุ่มประกอบรถเดิม.",
  "directCount": 3,
  "terms": {"MRO":"ศูนย์ซ่อมบำรุงอากาศยาน"},
  "items": [
    {"id":"20260801-a1","tag":"aero","rating":"green","title":"การบินไทยเซ็น contract ตั้งศูนย์ maintenance (MRO) อากาศยานที่อู่ตะเภา มูลค่าหมื่นล้าน","source":"Nation Thailand","date":"2026-07-28","url":"https://www.nationthailand.com/news/general/40069171","summary":"เช่าที่ EEC 50 ปี ตั้ง smart hangar ซ่อมเครื่องลำใหญ่ 3 ลำพร้อมกัน เริ่ม construction ปี 2027 เปิดปี 2030.","why":"MRO = งานลอก/ขัด/refinish ผิวเครื่องบิน ตลาด demand วัสดุขัดเกรดการบินกำลังเกิดในไทย ตรงกับดีล Hanko.","action":"เร่งดัน Hanko ให้จบ + วางตัวเป็น supplier วัสดุขัดตั้งแต่เฟส construction.","terms":{"contract":"สัญญา","maintenance":"การซ่อมบำรุง","MRO":"ศูนย์ซ่อมบำรุงอากาศยาน","hangar":"โรงซ่อมเครื่องบิน","construction":"การก่อสร้าง","refinish":"ขัด/พ่นผิวใหม่","demand":"ความต้องการ (ดีมานด์)","supplier":"ผู้ผลิต/ผู้จัดหา"}},
    {"id":"20260801-au2","tag":"auto","rating":"green","title":"Mitsubishi ทุ่ม investment เพิ่ม 1.6 หมื่นล้าน ปั้นฐาน production รถ EV กระบะ + e-Pajero","source":"Kaohoon","date":"2026-07-24","url":"https://www.kaohooninternational.com/economics/587469","summary":"ลงทุนถึงปี 2030 ใช้ไทยเป็นฐาน production หลัก ศึกษาผลิต/export กระบะไฟฟ้าและ Pajero ไฟฟ้า.","why":"ทุนญี่ปุ่น (ICP เรา) ยังปักหลัก ชิ้นส่วน EV รุ่นใหม่ = งานขัด/finishing ใหม่ๆ.","action":"หาช่องเข้าเสนอชิ้นส่วนสาย EV ของ supply chain Mitsubishi.","terms":{"investment":"การลงทุน","production":"การผลิต","export":"การส่งออก","finishing":"งานเก็บผิวงานให้เรียบ","supply chain":"ห่วงโซ่อุปทาน"}},
    {"id":"20260801-au3","tag":"auto","rating":"green","title":"ชิ้นส่วนยานยนต์ 2026–2028 โตจาก EV components","source":"Krungsri Research","date":"2026-07-01","url":"https://www.krungsri.com/en/research/industry/industry-outlook/hi-tech-industries/auto-parts/io/auto-parts-2026","summary":"capacity ผลิตชิ้นส่วน EV เพิ่ม หนุนด้วยนโยบายส่งเสริมและการใช้ local content.","why":"ชิ้นส่วน EV = งานเจียร/ขัด/surface finishing ดีมานด์วัสดุขัด B2B ตามเทรนด์นี้.","action":"ทำลิสต์โรงงานชิ้นส่วน EV รายใหม่ ไล่เข้าเสนอ.","terms":{"components":"ชิ้นส่วน","capacity":"กำลังการผลิต","local content":"สัดส่วนชิ้นส่วนในประเทศ","surface finishing":"การตกแต่งผิวงาน"}},
    {"id":"20260801-au4","tag":"auto","rating":"amber","title":"ส.อ.ท. หั่นเป้า production รถเหลือ 1.45 ล้านคัน EV จีนตี export","source":"Nation Thailand","date":"2026-07-24","url":"https://www.nationthailand.com/business/economy/40069108","summary":"มิ.ย. ผลิต 120,391 คัน ลด 7.6% export หด EV import >50% แย่งรถผลิตในไทย.","why":"โรงงาน assembly/ชิ้นส่วน ICE หดตัว = ลูกค้ากลุ่มนี้ของเราเสี่ยงลด order.","action":"กระจายความเสี่ยง เร่งย้ายน้ำหนักไปกลุ่ม EV + การบิน + DIY.","terms":{"production":"การผลิต","export":"การส่งออก","import":"การนำเข้า","assembly":"การประกอบ","order":"คำสั่งซื้อ (ออเดอร์)"}},
    {"id":"20260801-au5","tag":"auto","rating":"amber","title":"BYD แซง Toyota ขึ้นเบอร์ 1 ยอด booking EV+hybrid กิน 43.8%","source":"Bangkok Biznews","date":"2026-07-15","url":"https://www.bangkokbiznews.com/world/economics/1215044","summary":"ยอดจอง BYD 17,354 คัน แซงแชมป์เก่า Toyota market เอียงไปทางจีน/EV.","why":"supply chain เปลี่ยนขั้ว ใครเป็น supplier โรงงานจีนได้ก่อนได้เปรียบ.","action":"ศึกษาช่องเข้าโรงงาน BYD/ค่ายจีนในไทย.","terms":{"booking":"การจอง","hybrid":"รถไฮบริด (เครื่องยนต์+ไฟฟ้า)","market":"ตลาด","supply chain":"ห่วงโซ่อุปทาน","supplier":"ผู้จัดหา"}},
    {"id":"20260801-ae6","tag":"aero","rating":"amber","title":"การบินไทยรับ aircraft ใหม่ 28 ลำปีนี้ fleet แตะ 102 ลำ","source":"Kaohoon","date":"2026-07-20","url":"https://www.kaohooninternational.com/markets/583459","summary":"รับ Boeing 787 14 ลำ + A321neo 14 ลำ fleet โตจาก 80 เป็น 102.","why":"fleet โต = งาน maintenance ในประเทศโตตาม demand วัสดุซ่อม/ขัดเพิ่มระยะยาว.","action":"เก็บไว้ประกอบภาพตลาด MRO ที่กำลังโต.","terms":{"aircraft":"อากาศยาน/เครื่องบิน","fleet":"ฝูงบิน","maintenance":"การซ่อมบำรุง","demand":"ความต้องการ","MRO":"ศูนย์ซ่อมบำรุงอากาศยาน"}},
    {"id":"20260801-ae7","tag":"aero","rating":"amber","title":"บางกอกแอร์เวย์สลงทุน ~2 พันล้าน ตั้ง hangar ซ่อมเครื่อง narrow-body","source":"Nation Thailand","date":"2026-07-10","url":"https://www.nationthailand.com/business/corporate/40058574","summary":"สร้าง hangar ซ่อมเครื่องลำแคบเสริม ecosystem การบินไทยที่อู่ตะเภา.","why":"ผู้เล่น MRO เพิ่ม = customer base วัสดุขัดการบินขยาย ไม่ได้มีแค่การบินไทย.","action":"ทำรายชื่อผู้เล่น MRO ทั้งไซต์อู่ตะเภาไว้ตามทีหลัง.","terms":{"hangar":"โรงซ่อมเครื่องบิน","narrow-body":"เครื่องบินลำแคบ","ecosystem":"ระบบนิเวศ/เครือข่ายธุรกิจ","customer base":"ฐานลูกค้า","MRO":"ศูนย์ซ่อมบำรุงอากาศยาน"}}
  ]
};
